site_name: FiveOrbs Http
copyright: © 2023 ebene fünf GmbH
nav:
  - index.md
theme:
    name: fiveorbs
repo_url: https://github.com/fiveorbs/http
extra:
    project: Http
plugins:
    - search
    - macros:
        module_name: docs/main